### ISSUE TITLE
modelfit_results$parameter_estimates

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#455]
Pharmpy 0.38.0, r 4.1.1. When i extract results for run9.mod (see bottom of error) individually i can extract the parameters:

``` 
mod1 <- read_model(run9.mod)
mod_pars <- mod1$modelfit_results$parameter_estimates
```

however if i then use it within a map_df function using purrr it doesn't work anymore - i last ran this code on around the 23/7/2021:

```
read_results_wrapper <- function(res_path, ...) {
    # extract results for each cdd run and each drug
    readres <- read_model(res_path)
    # get parameter estimates for each cdd_run
    print('model_read')
    
    params <- readres$modelfit_results$parameter_estimates
    
    print('parameter est read')
    
    return(params)
    
  }

mod_res <- map_df(here('run9.mod'), read_results_wrapper)
```

I get the following error:

```
> py_last_error()
$type
[1] "AttributeError"

$value
[1] "'NoneType' object has no attribute 'expression'"

$traceback
[1] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 130, in modelfit_results\n    self.read_modelfit_results()\n"
[2] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 1037, in read_modelfit_results\n    self._modelfit_results = NONMEMChainedModelfitResults(ext_path, model=self)\n"
[3] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\results.py\", line 198, in __init__\n    self._read_ext_table()\n"
[4] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\results.py\", line 270, in _read_ext_table\n    ests = ests.rename(index=self.model.parameter_translation())\n"
[5] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 1008, in parameter_translation\n    self.parameters\n"
[6] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 281, in parameters\n    self.statements\n"
[7] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 412, in statements\n    comp = compartmental_model(self, advan, trans, des)\n"
[8] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\advan.py\", line 201, in compartmental_model\n    lhs_sum = dadt_dose.expression\n"

$message
[1] "AttributeError: 'NoneType' object has no attribute 'expression'"
```

run9.mod:

```
;; 1. Based on: 8
$PROBLEM    FE992026 CS001
$INPUT      ID TIME DV AGE SEX HT WT DOSE CMT=DROP AMT EVID MDV
$DATA      run8.dta IGNORE=@
$SUBROUTINE ADVAN6 TOL 5 DP
$MODEL      COMP=(DOSE,DEFDOSE) COMP=(CENT)
$PK 

  TVCL = THETA(1)
  TVV  = THETA(2)
  TVKA = THETA(3)
      
    CL    = TVCL*EXP(ETA(1)) 
    V     = TVV *EXP(ETA(2))  
    KA    = TVKA*EXP(ETA(3))   
    ALAG1=THETA(4)

$DES 
DADT(1) = -KA*A(1)
DADT(2) = KA*A(1)-(CL/V)*A(2)

$ERROR 
       IPRED = A(2)/V
       IRES  = DV-IPRED
       W     = THETA(5)
       IWRES = IRES/W       
       Y     = IPRED+W*EPS(1)

$THETA  (0,2604)
 (0,8892)
 (0,4.0439)
 (0,0.2,10)
 (0,0.8,10)
$OMEGA  BLOCK(2)
 0.256367
 0.270167 0.343359
$OMEGA  1.57143
$SIGMA  1  FIX
$ESTIMATION NOABORT PRINT=2 POSTHOC METHOD=1 INTER SADDLE_RESET=1 MAXEVAL=9990
$COVARIANCE PRECOND=1 PFCOND=1
$TABLE      ID TIME IPRED IWRES ONEHEADER NOPRINT FILE=sdtab9
$TABLE      ID ETA1 ETA2 ETA3 ONEHEADER NOPRINT FILE=patab9
$TABLE      ID DOSE TIME DV IPRED PRED CL V KA ALAG1 AGE WT ONEHEADER
            NOPRINT FILE=mytab9
```

**Comment by stellabelin** [comment]
Has been fixed.

**Comment by SCarter79** [comment]
The problem is the $DES when trying to extract cdd_results in pharmpy. Just checked with pharmr/pharmpy 0.46.1 using R 4.1.2 and the problem still remains. 

```
> py_last_error()
$type
[1] "AttributeError"

$value
[1] "'NoneType' object has no attribute 'expression'"

$traceback
[1] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 137, in modelfit_results\n    self.read_modelfit_results()\n"                                                     
[2] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 1123, in read_modelfit_results\n    self._modelfit_results = NONMEMChainedModelfitResults(ext_path, model=self)\n"
[3] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\results.py\", line 198, in __init__\n    self._read_ext_table()\n"                                                                 
[4] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\results.py\", line 270, in _read_ext_table\n    ests = ests.rename(index=self.model.parameter_translation())\n"                    
[5] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 1094, in parameter_translation\n    self.parameters\n"                                                            
[6] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 296, in parameters\n    self.statements\n"                                                                        
[7] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 417, in statements\n    comp = compartmental_model(self, advan, trans, des)\n"                                    
[8] "  File \"C:\\Users\\simca176\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\advan.py\", line 201, in compartmental_model\n    lhs_sum = dadt_dose.expression\n"                                                

$message
[1] "AttributeError: 'NoneType' object has no attribute 'expression'"

```

**Comment by rikardn** [comment]
This code has been revised since the bug was reported. If the problem remains we can open a new issue.
