### ISSUE TITLE
Identical datasets saved in .datasets in the run_iiv results

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#703]
I run run_iiv using v0.63.2 and found each candidate model has its own dataset saved in the folder .datasets and they are identical. I thought the idea is to save the datasets that have been changed.

**Comment by rikardn** [comment]
Sorry about this. There was a small issue causing this to not work in v0.63. We have fixed this in 0.64.1 which has been released.

**Comment by rosemarychen99** [comment]
I rerun it using v0.64.1. The issue still exists, i.e. there are respective dataset for all models.

**Comment by rikardn** [comment]
Ok, then I think this is related to the particular model/dataset being used. Could you email me the files that you used?

**Comment by rosemarychen99** [comment]
I run modelsearch using 0.66.0. And there is the same issue: there is a dataset for every model candidate

**Comment by rikardn** [comment]
#736 should fix this and is almost ready to merge
